
package tech.ngnydevices.aqualis._3_0;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-17T00:07:21.475+02:00
 * Generated source version: 3.2.4
 *
 */

public class HomingPortType_HomingPort_Server{

    protected HomingPortType_HomingPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HomingPortImpl();
        String address = "http://LIS1:4567/aqualis/HomingPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new HomingPortType_HomingPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
