
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tech.ngnydevices.aqualis._3_0;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-14T10:18:49.521+02:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "TestService",
                      portName = "HomingPort",
                      targetNamespace = "http://www.ngnydevices.tech/aqualis/3-0",
        wsdlLocation = CONF.LOCATION,
        endpointInterface = "tech.ngnydevices.aqualis._3_0.HomingPortType")

public class HomingPortImpl implements HomingPortType {

    private static final Logger LOG = Logger.getLogger(HomingPortImpl.class.getName());

    /* (non-Javadoc)
     * @see tech.ngnydevices.aqualis._3_0.HomingPortType#conveyorInitialization(tech.ngnydevices.aqualis._3_0.ConveyorInitialization body)*
     */
    public tech.ngnydevices.aqualis._3_0.ConveyorInitializationResponse conveyorInitialization(ConveyorInitialization body) {
        return  Main.random.nextObject(ConveyorInitializationResponse.class);
    }

}
