
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tech.ngnydevices.aqualis._3_0;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-08T00:40:27.798+02:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "TestService",
                      portName = "ResultServicePort",
                      targetNamespace = "http://www.ngnydevices.tech/aqualis/3-0",
                      wsdlLocation = CONF.LOCATION,
                      endpointInterface = "tech.ngnydevices.aqualis._3_0.ResultServicePortType")

public class ResultServicePortImpl implements ResultServicePortType {

    private static final Logger LOG = Logger.getLogger(ResultServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see tech.ngnydevices.aqualis._3_0.ResultServicePortType#sendResults(tech.ngnydevices.aqualis._3_0.SendResults body)*
     */
    public tech.ngnydevices.aqualis._3_0.SendResultsResponse sendResults(SendResults body) {
        return  Main.random.nextObject(SendResultsResponse.class);
    }

}
