
package tech.ngnydevices.aqualis._3_0;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-17T00:07:21.431+02:00
 * Generated source version: 3.2.4
 *
 */
public final class ResultServicePortType_ResultServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ngnydevices.tech/aqualis/3-0", "TestService");

    private ResultServicePortType_ResultServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TestService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TestService ss = new TestService(wsdlURL, SERVICE_NAME);
        ResultServicePortType port = ss.getResultServicePort();

        {
        System.out.println("Invoking sendResults...");
        tech.ngnydevices.aqualis._3_0.SendResults _sendResults_body = null;
        tech.ngnydevices.aqualis._3_0.SendResultsResponse _sendResults__return = port.sendResults(_sendResults_body);
        System.out.println("sendResults.result=" + _sendResults__return);


        }

        System.exit(0);
    }

}
