
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tech.ngnydevices.aqualis._3_0;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-08T00:40:27.775+02:00
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "TestService",
                      portName = "TestServicePort",
                      targetNamespace = "http://www.ngnydevices.tech/aqualis/3-0",
        wsdlLocation = CONF.LOCATION,
        endpointInterface = "tech.ngnydevices.aqualis._3_0.TestServicePortType")

public class TestServicePortImpl implements TestServicePortType {

    private static final Logger LOG = Logger.getLogger(TestServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see tech.ngnydevices.aqualis._3_0.TestServicePortType#getTests(tech.ngnydevices.aqualis._3_0.GetTests body)*
     */
    public tech.ngnydevices.aqualis._3_0.GetTestsResponse getTests(GetTests req) {

        GetTestsResponse q = new GetTestsResponse(); // Main.random.nextObject(GetTestsResponse.class);
        q.setPrimaryTube(req.getPrimaryTube());
        Tests t = new Tests();

        q.setResult(GetTestsResponseResult.SUCCESS);

        for (String s : new String[]{"A","B","C"}) {
            Tests.Test t1 = new Tests.Test();
            t1.setId(s);
            t.getTest().add(t1);
        }

        q.setTests(t);
        return q;
    }

}
